name: optimize-land-reg
services:
#  postgres:
#    image: 'postgres:latest'
#    environment:
#      - 'POSTGRES_DB=olr_db'
#      - 'POSTGRES_PASSWORD=P@$$w0rd'
#      - 'POSTGRES_USER=app'
#    ports:
#      - '5462'
  kafka:
    extends:
      file: ./kafka.yml
      service: kafka
  zookeeper:
    extends:
      file: ./kafka.yml
      service: zookeeper
