spring:
  application:
    name: optimize-land-reg
    version: 1.0.0
  profiles:
    active: local
  docker:
    compose:
      enabled: false
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: afis-master
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  jackson:
    serialization:
      fail-on-empty-beans: false
  boot:
    admin:
      client:
        url: http://localhost:1111
        instance:
#          service-base-url: http://localhost:1111
          service-host-type: IP
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: basic
